# check ./tina/utils/constant.py
model_post_train_dataset_name: salt_exp3
model_post_train_type: grpo
rl_post_train_reward_funcs:
- str_match
- format
rl_post_train_reward_weights:
- 2.0
- 1.0

# Model configs from trl
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
attn_implementation: flash_attention_2
use_peft: true
init_lora_weights: gaussian
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- down_proj
- up_proj
- gate_proj


# GRPO trainer configs from trl
bf16: true
use_vllm: true
vllm_device: cuda:0
vllm_gpu_memory_utilization: 0.45
vllm_max_model_len: 4096
gradient_accumulation_steps: 4 # 看起来到后期reward收敛了，那不如少一半step
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
log_completions: true
push_to_hub: false
hub_strategy: every_save
hub_private_repo: true
hub_model_id: salt-rl

learning_rate: 2e-05
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
max_prompt_length: 512
max_completion_length: 4096
max_steps: 360 # use 360 for lr scheduler but stop at 180 steps
num_generations: 8
num_train_epochs: 2
overwrite_output_dir: true
per_device_train_batch_size: 4
report_to:
- wandb

save_strategy: steps
save_steps: 25
save_total_limit: 1
save_weights_only_checkpoint: true

seed: 42
temperature: 0.8
warmup_ratio: 0.1
custom_system_prompt: |
  You are a responsible AI Assistant that provides thoughtful and accurate responses.
  You first think through the problem step-by-step in your internal monologue. Then, provide your final answer closed in <answer> </answer>. If you are uncertain about any part of the answer, clearly state "I am unsure."

  Respond in the following format:
  <think>
  Your detailed reasoning process
  </think>
  <answer>
  Your final answer if confident, or "I am unsure." if uncertain
  </answer>

custom_evaluation_prompt: |
  Who produces the Chevrolet Brookwood?